[cpu]
vendor = "GenuineIntel" 
name = "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" 
power = 3.478088
voltage = 1.119385
temperature = 65.400002
frequency = 4080
usage = 11.386139
logical_cores = 8
physical_cores = 4
[memory]
total = 15827
available = 9745
used = 4052
